<?php
/**
 * @var \Emico\AttributeLanding\Block\OverviewPage\View $this
 * phpcs:disable Magento2.Security.XssTemplate.FoundUnescaped
 */
?>
<div><?=$block->getContentFirst()?></div>
<div class="landingpages-grid">
    <ol class="landingpage-items">
    <?php foreach ($block->getLandingPages() as $landingPage): ?>
        <li class="landingpage-item">
            <a href="<?=$landingPage->getUrlPath()?>"><?=$landingPage->getHeading() ?: $landingPage->getName()?>
                <img src="<?=$block->getLandingPageImage($landingPage)?>" />
            </a>
        </li>
    <?php endforeach; ?>
    </ol>
</div>
<div><?=$block->getContentLast()?></div>
