name: Testing Suite
on: [push]
jobs:
  PHP:
    strategy:
      matrix:
        image: [
          'srcoder/development-php:php82-fpm'
        ]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Testing Suite
        run: |
          composer2 install --dev --prefer-dist --no-scripts --no-progress --optimize-autoloader --no-interaction -vvv
          composer2 show
          composer2 exec -v grumphp run
        shell: bash
